package app

import (
	"path/filepath"
	"strings"
	"testing"
)

func TestLegacyClaudeCodeNameStillSyncsClaude(t *testing.T) {
	home := t.TempDir()
	t.Setenv("HOME", home)
	fakePath(t, "claude")
	repoRoot := filepath.Join(home, ".agents")
	configPath := filepath.Join(repoRoot, "tackroom.yaml")
	writeSyncTestFile(t, configPath, []byte(`version: 1
agents:
  - name: claude-code
    enabled: true
    skill_root: ~/.claude/skills
    agent_root: ~/.claude/agents
    detect: claude
mcp_servers:
  - name: local
    enabled: true
    command: local-mcp
    agents: [claude-code]
hooks:
  - name: memory-stop
    enabled: true
    event: Stop
    command: ~/.agents/memory/hooks/stop.sh
    agents: [claude-code]
`))
	writeSyncTestFile(t, filepath.Join(repoRoot, "agents", "reviewer.md"), []byte("---\nname: reviewer\ndescription: Review code\n---\n\nReview carefully.\n"))

	if err := runSync(runOptions{ConfigPath: configPath, Agents: "claude-code"}); err != nil {
		t.Fatal(err)
	}
	assertFileContains(t, filepath.Join(home, ".claude.json"), []string{`"local"`, `"command": "local-mcp"`})
	assertFileContains(t, filepath.Join(home, ".claude", "settings.json"), []string{`"Stop"`, "stop.sh"})
	assertFileContains(t, filepath.Join(home, ".claude", "agents", "reviewer.md"), []string{"Generated by tackroom"})

	cfg, err := loadConfig(repoRoot, home, configPath)
	if err != nil {
		t.Fatal(err)
	}
	if cfg.Agents[0].Name != agentClaudeCode || cfg.MCPServers[0].Agents[0] != agentClaudeCode || cfg.Hooks[0].Agents[0] != agentClaudeCode {
		t.Fatalf("claude-code should load as %q: %+v", agentClaudeCode, cfg)
	}
}

func TestClaudeAndLegacyNameTogetherAreDuplicates(t *testing.T) {
	home := t.TempDir()
	path := filepath.Join(home, "tackroom.yaml")
	writeSyncTestFile(t, path, []byte(`version: 1
agents:
  - name: claude
    enabled: true
    skill_root: ~/.claude/skills
  - name: claude-code
    enabled: true
    skill_root: ~/.claude/skills
`))
	if _, err := loadConfig(home, home, path); err == nil || !strings.Contains(err.Error(), "duplicated") {
		t.Fatalf("err = %v, want a duplicate agent error", err)
	}
}
