package app

import (
	"encoding/json"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

type newHarnessCase struct {
	name, detect, skillRoot, agentRoot string
	roleFile, mcpFile, hookFile        string
	rootLink                           string
	mcpWant, hookWant                  []string
	preexisting                        map[string]string
}

func newHarnessCases(home string) []newHarnessCase {
	return []newHarnessCase{
		{
			name: agentCursor, detect: "cursor-agent", skillRoot: "~/.cursor/skills", agentRoot: "~/.cursor/agents",
			roleFile: filepath.Join(home, ".cursor", "agents", "reviewer.md"),
			mcpFile:  filepath.Join(home, ".cursor", "mcp.json"),
			hookFile: filepath.Join(home, ".cursor", "hooks.json"),
			mcpWant:  []string{`"mcpServers"`, `"local"`, `"command": "local-mcp"`, `"keep": "me"`},
			hookWant: []string{`"version": 1`, `"stop"`, `"command": "~/.agents/memory/hooks/stop.sh"`, `"timeout": 15`, `"afterFileEdit"`},
			preexisting: map[string]string{
				filepath.Join(home, ".cursor", "mcp.json"):   `{"keep":"me","mcpServers":{}}`,
				filepath.Join(home, ".cursor", "hooks.json"): `{"version":1,"hooks":{"afterFileEdit":[{"command":"./hooks/format.sh"}]}}`,
			},
		},
		{
			name: agentCopilot, detect: "copilot", skillRoot: "~/.copilot/skills", agentRoot: "~/.copilot/agents",
			roleFile: filepath.Join(home, ".copilot", "agents", "reviewer.agent.md"),
			mcpFile:  filepath.Join(home, ".copilot", "mcp-config.json"),
			hookFile: filepath.Join(home, ".copilot", "hooks", "tackroom.json"),
			rootLink: filepath.Join(home, ".copilot", "copilot-instructions.md"),
			mcpWant:  []string{`"type": "local"`, `"command": "local-mcp"`, `"tools": [`, `"*"`},
			hookWant: []string{`"version": 1`, `"Stop"`, `"command": "~/.agents/memory/hooks/stop.sh"`},
		},
		{
			name: agentGrok, detect: "grok", skillRoot: "~/.grok/skills", agentRoot: "~/.grok/agents",
			roleFile: filepath.Join(home, ".grok", "agents", "reviewer.md"),
			mcpFile:  filepath.Join(home, ".grok", "config.toml"),
			hookFile: filepath.Join(home, ".grok", "hooks", "tackroom.json"),
			rootLink: filepath.Join(home, ".grok", "AGENTS.md"),
			mcpWant:  []string{"[mcp_servers.local]", `command = "local-mcp"`, `model = "grok-4.6"`},
			hookWant: []string{`"Stop"`, `"type": "command"`, `"command": "~/.agents/memory/hooks/stop.sh"`},
			preexisting: map[string]string{
				filepath.Join(home, ".grok", "config.toml"): "model = \"grok-4.6\"\n",
			},
		},
	}
}

func writeNewHarnessRoot(t *testing.T, repoRoot string, c newHarnessCase) {
	t.Helper()
	writeSyncTestFile(t, filepath.Join(repoRoot, "tackroom.yaml"), []byte(`version: 1
agents:
  - name: `+c.name+`
    enabled: true
    skill_root: `+c.skillRoot+`
    agent_root: `+c.agentRoot+`
    detect: `+c.detect+`
mcp_servers:
  - name: local
    enabled: true
    command: local-mcp
    agents: [`+c.name+`]
hooks:
  - name: memory-stop
    enabled: true
    event: Stop
    command: ~/.agents/memory/hooks/stop.sh
    timeout: 15
    agents: [`+c.name+`]
  - name: notify
    enabled: true
    event: Notification
    command: ~/.agents/notify.sh
    agents: [`+c.name+`]
`))
	writeSyncTestFile(t, filepath.Join(repoRoot, "AGENTS.md"), []byte("# Shared instructions\n"))
	writeSyncTestFile(t, filepath.Join(repoRoot, "skills", "sample", "SKILL.md"), []byte("---\nname: sample\ndescription: sample skill\n---\n"))
	writeSyncTestFile(t, filepath.Join(repoRoot, "agents", "reviewer.md"), []byte("---\nname: reviewer\ndescription: Review code\ntools: [Read, Grep, Bash]\n---\n\nReview carefully.\n"))
}

func TestNewHarnessesSyncEndToEnd(t *testing.T) {
	for _, probe := range newHarnessCases("") {
		t.Run(probe.name, func(t *testing.T) {
			home := t.TempDir()
			t.Setenv("HOME", home)
			t.Setenv("COPILOT_HOME", "")
			t.Setenv("GROK_HOME", "")
			var c newHarnessCase
			for _, candidate := range newHarnessCases(home) {
				if candidate.name == probe.name {
					c = candidate
				}
			}
			fakePath(t, c.detect)
			repoRoot := filepath.Join(home, ".agents")
			writeNewHarnessRoot(t, repoRoot, c)
			for path, content := range c.preexisting {
				writeSyncTestFile(t, path, []byte(content))
			}
			configPath := filepath.Join(repoRoot, "tackroom.yaml")

			if err := runSync(runOptions{ConfigPath: configPath, Agents: c.name}); err != nil {
				t.Fatal(err)
			}

			role, err := os.ReadFile(c.roleFile)
			if err != nil || !strings.Contains(string(role), "Generated by tackroom") {
				t.Fatalf("role %s: %v\n%s", c.roleFile, err, role)
			}
			assertFileContains(t, c.mcpFile, c.mcpWant)
			assertFileContains(t, c.hookFile, c.hookWant)
			hooks, _ := os.ReadFile(c.hookFile)
			if strings.Contains(string(hooks), "notify.sh") && c.name != agentGrok {
				t.Fatalf("%s: unsupported Notification hook was written:\n%s", c.name, hooks)
			}
			if strings.HasSuffix(c.hookFile, ".json") {
				var parsed map[string]interface{}
				if err := json.Unmarshal(hooks, &parsed); err != nil {
					t.Fatalf("hook file is not valid JSON: %v\n%s", err, hooks)
				}
			}
			if c.rootLink != "" {
				if target, err := os.Readlink(c.rootLink); err != nil || target != filepath.Join(repoRoot, "AGENTS.md") {
					t.Fatalf("root instructions link %s = %q, %v", c.rootLink, target, err)
				}
			}
			mirror := filepath.Join(expandPath(c.skillRoot, home), "sample")
			if _, err := os.Lstat(mirror); !os.IsNotExist(err) {
				t.Fatalf("%s reads ~/.agents/skills natively; no mirror expected at %s (%v)", c.name, mirror, err)
			}

			before := snapshotFiles(t, c.roleFile, c.mcpFile, c.hookFile)
			if err := runSync(runOptions{ConfigPath: configPath, Agents: c.name}); err != nil {
				t.Fatal(err)
			}
			if after := snapshotFiles(t, c.roleFile, c.mcpFile, c.hookFile); after != before {
				t.Fatalf("second sync changed native files")
			}

			cfg, err := loadConfig(repoRoot, home, configPath)
			if err != nil {
				t.Fatal(err)
			}
			expected, err := expectedSkills(repoRoot, home, cfg)
			if err != nil {
				t.Fatal(err)
			}
			reports, err := inspectAgents(cfg.Agents, expected, repoRoot, home, cfg)
			if err != nil {
				t.Fatal(err)
			}
			r := reports[0]
			wantHooks := 1
			if c.name == agentGrok {
				wantHooks = 2 // Grok takes Claude Code event names as is, Notification included
			}
			if !r.Synced || len(r.ManagedMCP) != 1 || len(r.ManagedHook) != wantHooks || len(r.ManagedAgent) != 1 {
				t.Fatalf("after sync: synced=%v mcp=%v hooks=%v roles=%v unsupported=%v", r.Synced, r.ManagedMCP, r.ManagedHook, r.ManagedAgent, r.UnsupportedHook)
			}
			if c.name != agentGrok && (len(r.UnsupportedHook) != 1 || r.UnsupportedHook[0] != "notify") {
				t.Fatalf("Notification should be reported unsupported for %s: %v", c.name, r.UnsupportedHook)
			}
		})
	}
}

func TestNewHarnessesMirrorSkillsForOtherConfigRoots(t *testing.T) {
	for _, probe := range newHarnessCases("") {
		t.Run(probe.name, func(t *testing.T) {
			home := t.TempDir()
			t.Setenv("HOME", home)
			t.Setenv("COPILOT_HOME", "")
			t.Setenv("GROK_HOME", "")
			var c newHarnessCase
			for _, candidate := range newHarnessCases(home) {
				if candidate.name == probe.name {
					c = candidate
				}
			}
			fakePath(t, c.detect)
			repoRoot := filepath.Join(home, "elsewhere")
			writeNewHarnessRoot(t, repoRoot, c)
			if err := runSync(runOptions{ConfigPath: filepath.Join(repoRoot, "tackroom.yaml"), Agents: c.name}); err != nil {
				t.Fatal(err)
			}
			mirror := filepath.Join(expandPath(c.skillRoot, home), "sample", "SKILL.md")
			if _, err := os.Stat(mirror); err != nil {
				t.Fatalf("%s needs a skill mirror when the config root is not ~/.agents: %v", c.name, err)
			}
		})
	}
}

func TestCopilotAndGrokHonorHomeOverrides(t *testing.T) {
	home := t.TempDir()
	t.Setenv("HOME", home)
	copilotDir := filepath.Join(home, "copilot-elsewhere")
	grokDir := filepath.Join(home, "grok-elsewhere")
	t.Setenv("COPILOT_HOME", copilotDir)
	t.Setenv("GROK_HOME", grokDir)
	for _, c := range newHarnessCases(home)[1:] {
		fakePath(t, c.detect)
		repoRoot := filepath.Join(home, ".agents")
		writeNewHarnessRoot(t, repoRoot, c)
		if err := runSync(runOptions{ConfigPath: filepath.Join(repoRoot, "tackroom.yaml"), Agents: c.name}); err != nil {
			t.Fatal(err)
		}
	}
	for _, path := range []string{
		filepath.Join(copilotDir, "mcp-config.json"),
		filepath.Join(copilotDir, "hooks", "tackroom.json"),
		filepath.Join(copilotDir, "copilot-instructions.md"),
		filepath.Join(grokDir, "config.toml"),
		filepath.Join(grokDir, "hooks", "tackroom.json"),
		filepath.Join(grokDir, "AGENTS.md"),
	} {
		if _, err := os.Lstat(path); err != nil {
			t.Errorf("expected %s: %v", path, err)
		}
	}
	for _, dir := range []string{".copilot/hooks", ".grok/hooks"} {
		if _, err := os.Stat(filepath.Join(home, dir)); !os.IsNotExist(err) {
			t.Errorf("nothing should be written under ~/%s when the home override is set (%v)", dir, err)
		}
	}
}

func TestHookListAndRemoveForVersionedHookFiles(t *testing.T) {
	home := t.TempDir()
	path := filepath.Join(home, ".cursor", "hooks.json")
	writeSyncTestFile(t, path, []byte(`{"version":1,"hooks":{"stop":[{"command":"a.sh"},{"command":"b.sh"}]}}`))
	cfg := config{Hooks: []hookConfig{{Name: "a", Enabled: true, Event: "Stop", Command: "a.sh"}}}
	entries, _, err := collectNativeHooks(home, cfg, []agentConfig{{Name: agentCursor}})
	if err != nil {
		t.Fatal(err)
	}
	if len(entries) != 2 || !entries[0].Managed || entries[1].Managed {
		t.Fatalf("entries = %+v", entries)
	}
	if _, err := removeNativeHookEntries(entries[1:]); err != nil {
		t.Fatal(err)
	}
	data, _ := os.ReadFile(path)
	var parsed map[string]interface{}
	if err := json.Unmarshal(data, &parsed); err != nil || strings.Contains(string(data), "b.sh") || !strings.Contains(string(data), "a.sh") || parsed["version"] == nil {
		t.Fatalf("after remove (%v):\n%s", err, data)
	}
}

func assertFileContains(t *testing.T, path string, wants []string) {
	t.Helper()
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read %s: %v", path, err)
	}
	for _, want := range wants {
		if !strings.Contains(string(data), want) {
			t.Errorf("%s missing %q:\n%s", path, want, data)
		}
	}
}

func snapshotFiles(t *testing.T, paths ...string) string {
	t.Helper()
	var b strings.Builder
	for _, path := range paths {
		data, err := os.ReadFile(path)
		if err != nil {
			t.Fatalf("read %s: %v", path, err)
		}
		b.WriteString(path)
		b.Write(data)
	}
	return b.String()
}
