// Package agentrole parses canonical tackroom roles and projects them into
// harness-native role formats.
package agentrole

import (
	"path/filepath"
	"strconv"
	"strings"
)

const (
	// MarkdownExtension is the canonical editable role source extension.
	MarkdownExtension = ".md"
	// GeneratedMarker identifies role projections owned by tackroom.
	GeneratedMarker = "Generated by tackroom"
	// LegacyGeneratedMarker identifies role projections written before the
	// rename from dotagents; sync adopts and rewrites them.
	LegacyGeneratedMarker = "Generated by dotagents"
)

// Role is the canonical representation shared by every harness renderer.
type Role struct {
	Name         string          `yaml:"name"`
	Description  string          `yaml:"description"`
	Model        string          `yaml:"model"`
	Effort       string          `yaml:"effort"`
	Tools        []string        `yaml:"tools"`
	Color        string          `yaml:"color"`
	Instructions string          `yaml:"-"`
	Source       string          `yaml:"-"`
	Claude       ClaudeOptions   `yaml:"claude"`
	Codex        CodexOptions    `yaml:"codex"`
	OMP          OMPOptions      `yaml:"omp"`
	Pi           PiOptions       `yaml:"pi"`
	Droid        DroidOptions    `yaml:"droid"`
	Opencode     OpenCodeOptions `yaml:"opencode"`
	Qwen         QwenOptions     `yaml:"qwen"`
	Cursor       CursorOptions   `yaml:"cursor"`
	Copilot      CopilotOptions  `yaml:"copilot"`
	Grok         GrokOptions     `yaml:"grok"`
}

type ClaudeOptions struct {
	Model string `yaml:"model"`
}

type CodexOptions struct {
	Model                string `yaml:"model"`
	ModelReasoningEffort string `yaml:"model_reasoning_effort"`
}

type OMPOptions struct {
	Model         string `yaml:"model"`
	ThinkingLevel string `yaml:"thinking-level"`
}

type PiOptions struct {
	Model    string `yaml:"model"`
	Thinking string `yaml:"thinking"`
}

type DroidOptions struct {
	Model           string   `yaml:"model"`
	ReasoningEffort string   `yaml:"reasoning_effort"`
	Tools           []string `yaml:"tools"`
}

type OpenCodeOptions struct {
	Model       string `yaml:"model"`
	Temperature string `yaml:"temperature"`
	Mode        string `yaml:"mode"`
}

type QwenOptions struct {
	Model        string   `yaml:"model"`
	ApprovalMode string   `yaml:"approval_mode"`
	Tools        []string `yaml:"tools"`
}

type CursorOptions struct {
	Model    string `yaml:"model"`
	Readonly bool   `yaml:"readonly"`
}

type CopilotOptions struct {
	Model string `yaml:"model"`
}

type GrokOptions struct {
	Model string `yaml:"model"`
}

// Renderer is a harness projection of a canonical role.
type Renderer interface {
	Extension() string
	Render(Role) string
}

type renderer struct {
	extension string
	render    func(Role) string
}

func (r renderer) Extension() string       { return r.extension }
func (r renderer) Render(role Role) string { return r.render(role) }

var renderers = map[string]Renderer{
	"claude":    renderer{extension: ".md", render: renderClaude},
	"codex":     renderer{extension: ".toml", render: renderCodex},
	"droid":     renderer{extension: ".md", render: renderDroid},
	"opencode":  renderer{extension: ".md", render: renderOpenCode},
	"pi":        renderer{extension: ".md", render: renderPi},
	"omp":       renderer{extension: ".md", render: renderOMP},
	"qwen-code": renderer{extension: ".md", render: renderQwen},
	"cursor":    renderer{extension: ".md", render: renderCursor},
	"copilot":   renderer{extension: ".agent.md", render: renderCopilot},
	"grok":      renderer{extension: ".md", render: renderGrok},
}

// Lookup returns the registered renderer for a harness name.
func Lookup(harness string) (Renderer, bool) {
	renderer, ok := renderers[strings.ToLower(strings.TrimSpace(harness))]
	return renderer, ok
}

func sourceLabel(role Role) string {
	if role.Source == "" {
		return "agents/" + role.Name + MarkdownExtension
	}
	return "agents/" + filepath.Base(role.Source)
}

func writeYAMLScalar(b *strings.Builder, key, value string) {
	value = strings.TrimSpace(value)
	if value == "" {
		return
	}
	b.WriteString(key)
	b.WriteString(": ")
	b.WriteString(strconv.Quote(value))
	b.WriteString("\n")
}

func writeYAMLListItem(b *strings.Builder, value string) {
	value = strings.TrimSpace(value)
	if value == "" {
		return
	}
	b.WriteString("  - ")
	b.WriteString(strconv.Quote(value))
	b.WriteString("\n")
}

func writeTOMLString(b *strings.Builder, key, value string) {
	value = strings.TrimSpace(value)
	if value == "" {
		return
	}
	b.WriteString(key)
	b.WriteString(" = ")
	b.WriteString(strconv.Quote(value))
	b.WriteString("\n")
}

func writeGeneratedMarkdownBody(b *strings.Builder, role Role) {
	b.WriteString("---\n\n<!-- ")
	b.WriteString(GeneratedMarker)
	b.WriteString(" from ")
	b.WriteString(sourceLabel(role))
	b.WriteString("; do not edit directly. -->\n\n")
	b.WriteString(role.Instructions)
	b.WriteString("\n")
}

func canonicalModelTier(model string) bool {
	switch strings.ToLower(strings.TrimSpace(model)) {
	case "haiku", "sonnet", "opus":
		return true
	}
	return false
}

func mappedTools(tools []string, mapping map[string]string) []string {
	out := make([]string, 0, len(tools))
	seen := make(map[string]struct{}, len(tools))
	for _, tool := range tools {
		mapped := mapping[strings.ToLower(strings.TrimSpace(tool))]
		if mapped == "" {
			continue
		}
		if _, ok := seen[mapped]; ok {
			continue
		}
		seen[mapped] = struct{}{}
		out = append(out, mapped)
	}
	return out
}
