package agentrole

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestRendererRegistryByteStableOutputs(t *testing.T) {
	role := Role{
		Name:         "reviewer",
		Description:  "Review: safely",
		Model:        "opus",
		Effort:       "high",
		Tools:        []string{"Read", "WebSearch", "Write"},
		Color:        "purple",
		Instructions: "Review carefully.",
		Source:       filepath.Join("somewhere", "reviewer.md"),
		Claude:       ClaudeOptions{Model: "claude-custom"},
		Codex:        CodexOptions{Model: "gpt-custom", ModelReasoningEffort: "max"},
		Droid:        DroidOptions{},
		Opencode:     OpenCodeOptions{Model: "anthropic/claude", Temperature: "0.1", Mode: "primary"},
		OMP:          OMPOptions{Model: "gpt-omp", ThinkingLevel: "max"},
		Qwen:         QwenOptions{ApprovalMode: "plan"},
	}
	tests := map[string]struct {
		extension string
		want      string
	}{
		"claude-code": {".md", "---\nname: \"reviewer\"\ndescription: \"Review: safely\"\nmodel: \"claude-custom\"\neffort: \"high\"\ntools: Read, WebSearch, Write\ncolor: \"purple\"\n---\n\n<!-- Generated by tackroom from agents/reviewer.md; do not edit directly. -->\n\nReview carefully.\n"},
		"codex":       {".toml", "# Generated by tackroom from agents/reviewer.md; do not edit directly.\nname = \"reviewer\"\ndescription = \"Review: safely\"\nmodel = \"gpt-custom\"\nmodel_reasoning_effort = \"max\"\ndeveloper_instructions = \"Review carefully.\"\n"},
		"droid":       {".md", "---\nname: \"reviewer\"\ndescription: \"Review: safely\"\nmodel: \"custom:gpt-5.5(high)\"\nreasoningEffort: \"high\"\ntools:\n  - \"Read\"\n  - \"WebSearch\"\n  - \"Create\"\n  - \"Edit\"\n---\n\n<!-- Generated by tackroom from agents/reviewer.md; do not edit directly. -->\n\nReview carefully.\n"},
		"opencode":    {".md", "---\ndescription: \"Review: safely\"\nmode: primary\nmodel: \"anthropic/claude\"\ntemperature: 0.1\n---\n\n<!-- Generated by tackroom from agents/reviewer.md; do not edit directly. -->\n\nReview carefully.\n"},
		"pi":          {".md", "---\nname: \"reviewer\"\ndescription: \"Review: safely\"\nthinking: \"high\"\ntools:\n  - \"read\"\n  - \"web_search\"\n  - \"write\"\n---\n\n<!-- Generated by tackroom from agents/reviewer.md; do not edit directly. -->\n\nReview carefully.\n"},
		"omp":         {".md", "---\nname: \"reviewer\"\ndescription: \"Review: safely\"\nmodel:\n  - \"gpt-omp\"\nthinking-level: \"max\"\ntools:\n  - \"read\"\n  - \"web_search\"\n  - \"write\"\n---\n\n<!-- Generated by tackroom from agents/reviewer.md; do not edit directly. -->\n\nReview carefully.\n"},
		"qwen-code":   {".md", "---\nname: \"reviewer\"\ndescription: \"Review: safely\"\nmodel: \"inherit\"\napprovalMode: \"plan\"\ntools:\n  - \"read_file\"\n  - \"web_search\"\n  - \"write_file\"\n---\n\n<!-- Generated by tackroom from agents/reviewer.md; do not edit directly. -->\n\nReview carefully.\n"},
	}
	for harness, test := range tests {
		t.Run(harness, func(t *testing.T) {
			renderer, ok := Lookup(harness)
			if !ok {
				t.Fatalf("renderer %q not registered", harness)
			}
			if got := renderer.Extension(); got != test.extension {
				t.Fatalf("extension = %q, want %q", got, test.extension)
			}
			if got := renderer.Render(role); got != test.want {
				t.Fatalf("rendered bytes differ\n--- got ---\n%s--- want ---\n%s", got, test.want)
			}
		})
	}
	if _, ok := Lookup("unknown"); ok {
		t.Fatal("unknown harness unexpectedly has a role renderer")
	}
}

func TestParseMarkdownSupportsToolShapesAndHarnessOverrides(t *testing.T) {
	for name, tools := range map[string]string{
		"list":   "tools: [Read, Grep]",
		"scalar": "tools: Read, Grep",
	} {
		t.Run(name, func(t *testing.T) {
			role, err := ParseMarkdown("agents/builder.md", []byte("---\nname: builder\ndescription: Builds features\nmodel: opus\n"+tools+"\nqwen:\n  model: qwen-custom\n  approval_mode: plan\n---\n\nBuild carefully.\n"))
			if err != nil {
				t.Fatal(err)
			}
			if len(role.Tools) != 2 || role.Tools[0] != "Read" || role.Tools[1] != "Grep" {
				t.Fatalf("tools = %#v", role.Tools)
			}
			if role.Qwen.Model != "qwen-custom" || role.Qwen.ApprovalMode != "plan" {
				t.Fatalf("Qwen options = %#v", role.Qwen)
			}
		})
	}
}

func TestParseMarkdownRejectsMappingTools(t *testing.T) {
	_, err := ParseMarkdown("agents/invalid.md", []byte("---\nname: invalid\ndescription: Invalid\ntools: {name: Read}\n---\n\nDo work.\n"))
	if err == nil || err.Error() != "parse agents/invalid.md frontmatter: tools must be a YAML sequence or comma-separated string" {
		t.Fatalf("error = %v", err)
	}
}

func TestRendererModelFallbackRules(t *testing.T) {
	base := Role{Name: "builder", Description: "Builds", Model: "opus", Instructions: "Build."}
	tests := map[string][]string{
		"claude-code": {`model: "opus"`},
		"codex":       {`!model =`},
		"droid":       {`model: "custom:gpt-5.5(high)"`},
		"opencode":    {`!model:`},
		"pi":          {`!model:`},
		"omp":         {"model:\n  - \"opus\""},
		"qwen-code":   {`model: "inherit"`},
	}
	for harness, assertions := range tests {
		t.Run(harness, func(t *testing.T) {
			renderer, _ := Lookup(harness)
			got := renderer.Render(base)
			for _, assertion := range assertions {
				if strings.HasPrefix(assertion, "!") {
					if strings.Contains(got, strings.TrimPrefix(assertion, "!")) {
						t.Fatalf("unexpected %q in:\n%s", assertion[1:], got)
					}
					continue
				}
				if !strings.Contains(got, assertion) {
					t.Fatalf("missing %q in:\n%s", assertion, got)
				}
			}
		})
	}
}

func TestLoadValidatesCanonicalRoles(t *testing.T) {
	root := t.TempDir()
	dir := filepath.Join(root, "agents")
	if err := os.MkdirAll(dir, 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(dir, "invalid.md"), []byte("---\nname: invalid\ndescription: Missing body\n---\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	if _, err := Load(root); err == nil || !strings.Contains(err.Error(), "missing instructions") {
		t.Fatalf("Load error = %v", err)
	}
}
